spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: ${MONGODB_URI}

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: auth-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


jwt:
  secret: ${JWT_SECRET}
  issuer: "market-auth-service"

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.mongodb.driver: WARN
