spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: auth-service

  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: ${JWT_SECRET}
  issuer: "market-auth-service"

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.mongodb.driver: WARN
