spring:
  application:
    name: auth-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: auth-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username=${KAFKA_USERNAME}
        password=${KAFKA_PASSWORD};


server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.mongodb.driver: WARN

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: "market-auth-service"
    expiration-ms: 3600000
